services:
  - type: web
    name: climate-stories-map
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r backend/requirements.txt
      
      # Install Node.js dependencies and build frontend
      cd frontend && npm install && npm run build
      
      # Create static directory in backend and copy frontend build
      mkdir -p ../backend/static
      cp -R dist/* ../backend/static/
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CAPTCHA_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0